### PR TITLE
Slk deforestation blogpost v2

### PR DESCRIPTION
**Pull request by WinnieYap-CorrelAid**

### CODE REVIEW

**Comment by ajg54** [comment]
Thanks for this, Winnie. Did you have any challenges getting this to work or where the instructions in the readme file clear enough? Feedback on the PR:
- Under 'What is SLK?' there is a reference to LINK rather than having the actual link included.
- The image that appears on the post page itself renders on my machine such that the start and end of the text is cut-off. If it was resized, this can perhaps be avoided.
- The commit messages are not descriptive, although this might have been in part because you made the post/changes prior to having proper access to the repo. There is nothing to change here, but for next time it'll be helpful to have more meaningful commit messages.
- It could be nice to add a link to this post in the old project post about this project, e.g. by adding a final line that says there is a now a blogpost with more details (with link to the new blogpost).

Otherwise it looks good to me. When running locally it worked as expected and also when rebuilding for deployment it generated essentially the same website. Annoyingly on our machines the line spacing of the files is rendered differently, so it shows _differences_ in all files, but none that actually make any real difference to the website.

**Very impressive that you managed to get this working without any instruction / support.**

**Comment by WinnieYap-CorrelAid** [comment]
Hi Alexis,

Thank you for your feedback

I had some issues getting it to work but all in all it was doable 😃

I'll have a look at your comments and upload/commit a updated files later today!

Best, Winnie

**Comment by WinnieYap-CorrelAid** [comment]
Hi Alexis,
I processed your changes and commited them just now.
Please can you have a second look?
Many thanks!
Winnie

**Review by ajg54 — APPROVED** [review]
Looks awesome, thanks. Will merge and do a quick double check that the deployment has worked.

**Comment by ajg54** [comment]
The changes are live now and look good. Great job.

**Pull request merged**
